{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tycho-indexer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tycho-indexer.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if or .Values.serviceAccount.annotations .Values.annotations }}
  annotations:
    {{- if .Values.annotations }}
    {{- toYaml .Values.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
{{- if hasKey .Values.serviceAccount "automount" }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.imagePullSecrets | nindent 2 }}
{{- end }}
{{- end }}
